### PR TITLE
fix: songs pausing or not playing as expected

### LINKED ISSUE #310: Festify autopauses
First off .... I LOVE festify!! Great for parties! 
Recently I noticed that after three songs, Festify will auto pause. I have tried flushing the queue, updating browser, different browser, updating spotify, and restarting PC. 
I have tried with both Chrome and Firefox and it does the same thing. 
Any suggestions would be super appreciated!
Thank you!
Kathy

### PR DESCRIPTION
**Pull request by leolabs**
This hopefully fixes #310 and #272 some other issues that arise when Spotify's API is acting up.

### CODE REVIEW

File: src/actions/view-party-settings.ts [hunk 1]
```diff
@@ -165,15 +153,8 @@ export async function insertPlaylist(
...
-                .filter(
-                    it =>
-                        it &&
-                        !it.is_local &&
-                        it.track &&
-                        it.track.id &&
-                        it.track.is_playable !== false,
-                )
-                .map(it => it.track);
+                .filter((it) => it && !it.is_local && it.track.id && it.track.is_playable !== false)
```
Comment (NeoLegends) [inline src/actions/view-party-settings.ts:156]: This is missing the check for `it.track`, is this intentional?

**Review by NeoLegends — APPROVED** [review]
One question but I think it might not be relevant.

mostly LGTM!

File: src/actions/view-party-settings.ts (hunk 1 above)
Comment (leolabs) [reply src/actions/view-party-settings.ts:156]: The Spotify types specify that `track` is never undefined, so I removed the check for it. In case it might be undefined, the check for `it.track.id` would resolve to false.

**Comment by o-coster** [comment]
When is this going to be merged? Looking forward to enjoy Festify without pauses again!
